import { z } from 'zod';

/**
 * User schema for validation
 * Defines the structure and validation rules for user data
 */
export const userSchema = z.object({
  id: z.string(),
  name: z.string().min(2, 'Name must be at least 2 characters'),
  last_name: z.string().min(2, 'Last name must be at least 2 characters'),
  email: z.string().email('Invalid email address'),
  user_type: z.enum(['admin', 'user'], {
    errorMap: () => ({ message: 'User type must be admin or user' })
  }),
  picture: z.string().optional(),
  user_name: z.string().min(3, 'Username must be at least 3 characters'),
  created_at: z.string().datetime(),
  updated_at: z.string().datetime()
});

/**
 * Schema for creating a new user
 * Omits id and timestamps as they are generated by the server
 */
export const createUserSchema = userSchema.omit({ 
  id: true, 
  created_at: true, 
  updated_at: true 
});

/**
 * Schema for updating an existing user
 * Makes all fields optional except id
 */
export const updateUserSchema = userSchema.partial().extend({
  id: z.string()
});

// TypeScript types derived from schemas
export type User = z.infer<typeof userSchema>;
export type CreateUser = z.infer<typeof createUserSchema>;
export type UpdateUser = z.infer<typeof updateUserSchema>;